# Site settings
title: Ryan P. Jones
email: ryanpjones2009@gmail.com
description: |
  Since having earned his BFA in Performing Arts emphasizing in
  Technical Theatre from Southeast Missouri State University in 2012,
  Ryan P. Jones has worked in many different areas around the United
  States.  In 2014, he was excited to join the Actors Equity
  Association.  He is now pursuing his MFA in Stage Management from
  Wayne State University in Detroit, MI, where he anticipates
  graduation in 2017.
baseurl: ""
url: "http://www.ryanpjones.com"

# Build settings
markdown: kramdown
permalink: pretty
